apiVersion: v1
kind: Service
metadata:
  name: toolbox-redis
  namespace: sre-toolbox
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: toolbox-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-redis
  namespace: sre-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox-redis
  template:
    metadata:
      labels:
        app: toolbox-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
